version: "3.9"
services:
  typescript-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "5000:5000"
    links:
      - monguito
    volumes:
      - .:/home/app
  monguito:
    image: mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME= 
      - MONGO_INITDB_ROOT_PASSWORD= 
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data: